# Generated by Django 3.2.3 on 2024-03-16 17:40

from django.db import migrations, models
import rest_framework.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240316_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag', validators=[rest_framework.validators.UniqueValidator], verbose_name='Тэги'),
        ),
    ]
